import type { NichePack } from './nichePack.ts';

/**
 * The 50-item business-niche seed list (spec Phase 3). Every string here is
 * original, niche-native business language authored for this project.
 */
export const nichePacks: readonly NichePack[] = [
  {
    id: 'wedding-photography',
    label: 'Wedding Photography Studio',
    venture: 'studio',
    team: 'shooting crew',
    customers: 'couples',
    pressureLabel: 'Booking droughts & market saturation',
    pressureDesc:
      'Seasonal booking droughts and a saturated local market slowly erode an unattended studio: rival portfolios crowd the feeds and inquiry volume decays until actively countered.',
    pressureSources: 'oversaturated venues',
    gearTerm: 'Camera & lens kit',
    inquiriesTerm: 'Booking inquiries',
    peakSeason: 'Wedding season',
    slowSeason: 'Off-season',
    crunchSeason: 'Recession pullback',
    scene: 'Golden-hour portrait session',
  },
  {
    id: 'artisan-bakery',
    label: 'Artisan Bakery',
    venture: 'bakery',
    team: 'baking team',
    customers: 'regulars',
    pressureLabel: 'Supermarket squeeze & flour-cost creep',
    pressureDesc:
      'Chain-store discounting and creeping ingredient costs quietly eat margins; left unattended, footfall drifts to the supermarket aisle.',
    pressureSources: 'discount-chain corridors',
    gearTerm: 'Ovens & proofing racks',
    inquiriesTerm: 'Counter footfall',
    peakSeason: 'Holiday rush',
    slowSeason: 'Quiet weeks',
    crunchSeason: 'Wheat-price spike',
    scene: 'Dawn batch out of the oven',
  },
  {
    id: 'craft-brewery',
    label: 'Craft Brewery',
    venture: 'brewery',
    team: 'brew crew',
    customers: 'taproom patrons',
    pressureLabel: 'Tap-list churn & macro-lager pricing',
    pressureDesc:
      'Distributors rotate tap lines toward cheaper macro brands while novelty-chasing drinkers drift; shelf presence decays unless actively defended.',
    pressureSources: 'contested tap accounts',
    gearTerm: 'Fermenters & kegs',
    inquiriesTerm: 'Taproom traffic',
    peakSeason: 'Festival summer',
    slowSeason: 'Dry January trough',
    crunchSeason: 'Hop-contract crunch',
    scene: 'First pour of a new batch',
  },
  {
    id: 'boutique-fitness-studio',
    label: 'Boutique Fitness Studio',
    venture: 'studio',
    team: 'coaching staff',
    customers: 'members',
    pressureLabel: 'Membership churn & big-box undercutting',
    pressureDesc:
      'Resolution-cycle dropouts and cut-price gym chains bleed the member base month over month unless retention is worked deliberately.',
    pressureSources: 'lapsed-member cohorts',
    gearTerm: 'Rigs & training equipment',
    inquiriesTerm: 'Trial sign-ups',
    peakSeason: 'New-year surge',
    slowSeason: 'Summer slump',
    crunchSeason: 'Disposable-income squeeze',
    scene: 'Packed morning class',
  },
  {
    id: 'mobile-pet-grooming',
    label: 'Mobile Pet Grooming Service',
    venture: 'grooming service',
    team: 'groomers',
    customers: 'pet parents',
    pressureLabel: 'Route decay & franchise encroachment',
    pressureDesc:
      'National franchises leaflet your best streets while no-show appointments hollow out routes; an untended calendar decays into dead mileage.',
    pressureSources: 'franchise-blitzed suburbs',
    gearTerm: 'Vans & grooming stations',
    inquiriesTerm: 'Appointment requests',
    peakSeason: 'Shedding season',
    slowSeason: 'Holiday lull',
    crunchSeason: 'Fuel-price spike',
    scene: 'Freshly groomed golden retriever',
  },
  {
    id: 'board-game-cafe',
    label: 'Board Game Café',
    venture: 'café',
    team: 'game hosts',
    customers: 'table guests',
    pressureLabel: 'Screen-time drift & rent escalation',
    pressureDesc:
      'Digital entertainment quietly siphons weeknight tables while the landlord ratchets rent; empty chairs compound unless events keep pulling people in.',
    pressureSources: 'dead weeknight slots',
    gearTerm: 'Game library & tables',
    inquiriesTerm: 'Table reservations',
    peakSeason: 'Convention buzz',
    slowSeason: 'Exam-season quiet',
    crunchSeason: 'Rent-review squeeze',
    scene: 'Full house on tournament night',
  },
  {
    id: 'farm-to-table-restaurant',
    label: 'Farm-to-Table Restaurant',
    venture: 'restaurant',
    team: 'kitchen brigade',
    customers: 'diners',
    pressureLabel: 'Review erosion & produce volatility',
    pressureDesc:
      'One slow week of mixed reviews and a wobbly supplier can start a slide in covers that compounds; reputation decays faster than it builds.',
    pressureSources: 'cold review threads',
    gearTerm: 'Kitchen line & cold storage',
    inquiriesTerm: 'Reservations',
    peakSeason: 'Harvest menu season',
    slowSeason: 'Post-holiday quiet',
    crunchSeason: 'Produce-price shock',
    scene: 'Chef plating the tasting menu',
  },
  {
    id: 'vintage-clothing-boutique',
    label: 'Vintage Clothing Boutique',
    venture: 'boutique',
    team: 'stylists',
    customers: 'collectors',
    pressureLabel: 'Fast-fashion flood & resale-app leakage',
    pressureDesc:
      'Fast-fashion lookalikes and phone-first resale apps skim your buyers; an uncurated rack goes stale and the racks stop turning.',
    pressureSources: 'resale-app strongholds',
    gearTerm: 'Racks & fitting rooms',
    inquiriesTerm: 'Walk-in browsers',
    peakSeason: 'Festival & prom season',
    slowSeason: 'Mid-winter lull',
    crunchSeason: 'Discretionary-spend squeeze',
    scene: 'A one-of-a-kind find on the rack',
  },
  {
    id: 'coworking-space',
    label: 'Coworking Space',
    venture: 'space',
    team: 'community managers',
    customers: 'members',
    pressureLabel: 'Desk churn & home-office gravity',
    pressureDesc:
      'Remote workers drift back to kitchen tables and startups fold or graduate; unmanaged occupancy leaks a few desks every month.',
    pressureSources: 'half-empty floors',
    gearTerm: 'Desks & meeting rooms',
    inquiriesTerm: 'Tour bookings',
    peakSeason: 'Funding-cycle spring',
    slowSeason: 'August ghost town',
    crunchSeason: 'Startup funding winter',
    scene: 'Buzzing open-plan floor',
  },
  {
    id: 'food-truck',
    label: 'Gourmet Food Truck',
    venture: 'truck',
    team: 'line crew',
    customers: 'lunch crowds',
    pressureLabel: 'Pitch competition & permit friction',
    pressureDesc:
      'Rival trucks camp the best corners and permit rules shift underfoot; an unworked pitch rotation bleeds covers day by day.',
    pressureSources: 'contested corners',
    gearTerm: 'Truck & griddle line',
    inquiriesTerm: 'Queue length',
    peakSeason: 'Street-festival summer',
    slowSeason: 'Rainy-week trough',
    crunchSeason: 'Fuel & permit squeeze',
    scene: 'Lunch-rush queue around the block',
  },
  {
    id: 'landscaping-service',
    label: 'Landscaping Service',
    venture: 'service',
    team: 'field crews',
    customers: 'homeowners',
    pressureLabel: 'Contract churn & gig-app undercutting',
    pressureDesc:
      'Gig apps undercut maintenance contracts and one missed mow loses a street of referrals; the book of business erodes without steady account care.',
    pressureSources: 'poached subdivisions',
    gearTerm: 'Mowers & trailers',
    inquiriesTerm: 'Quote requests',
    peakSeason: 'Growing season',
    slowSeason: 'Dormant winter',
    crunchSeason: 'Drought restrictions',
    scene: 'A finished front-yard transformation',
  },
  {
    id: 'house-cleaning-service',
    label: 'House Cleaning Service',
    venture: 'service',
    team: 'cleaning teams',
    customers: 'households',
    pressureLabel: 'Platform commissions & schedule churn',
    pressureDesc:
      'Booking platforms take a widening cut while cancellations punch holes in routes; unmanaged, the weekly book quietly thins out.',
    pressureSources: 'platform-locked postcodes',
    gearTerm: 'Supply kits & vehicles',
    inquiriesTerm: 'Booking requests',
    peakSeason: 'Spring-clean rush',
    slowSeason: 'Holiday-travel lull',
    crunchSeason: 'Cost-of-living pinch',
    scene: 'A spotless handover walkthrough',
  },
  {
    id: 'daycare-center',
    label: 'Daycare Center',
    venture: 'center',
    team: 'educators',
    customers: 'families',
    pressureLabel: 'Enrollment churn & staffing gaps',
    pressureDesc:
      'Families relocate, subsidies shift, and one educator resignation caps your licensed ratio; enrollment decays unless the waitlist is actively cultivated.',
    pressureSources: 'waitlist dead zones',
    gearTerm: 'Classrooms & play yards',
    inquiriesTerm: 'Enrollment inquiries',
    peakSeason: 'Back-to-work autumn',
    slowSeason: 'Summer-holiday dip',
    crunchSeason: 'Subsidy-review freeze',
    scene: 'Story time on the reading rug',
  },
  {
    id: 'tutoring-center',
    label: 'Tutoring Center',
    venture: 'center',
    team: 'tutors',
    customers: 'students',
    pressureLabel: 'App-based rivals & exam-cycle whiplash',
    pressureDesc:
      'Free tutoring apps and AI homework helpers skim casual demand while enrollments crater the week after exams; the roster shrinks without re-engagement.',
    pressureSources: 'app-first households',
    gearTerm: 'Classrooms & materials',
    inquiriesTerm: 'Assessment bookings',
    peakSeason: 'Exam-prep season',
    slowSeason: 'Summer break',
    crunchSeason: 'Household budget squeeze',
    scene: 'A breakthrough at the whiteboard',
  },
  {
    id: 'dental-practice',
    label: 'Dental Practice',
    venture: 'practice',
    team: 'clinical staff',
    customers: 'patients',
    pressureLabel: 'Insurance squeeze & recall lapse',
    pressureDesc:
      'Reimbursement rates ratchet down while patients quietly skip recalls; an unworked recall list decays into an empty hygiene book.',
    pressureSources: 'lapsed recall lists',
    gearTerm: 'Chairs & imaging suite',
    inquiriesTerm: 'New-patient calls',
    peakSeason: 'Benefits-deadline rush',
    slowSeason: 'Summer vacation dip',
    crunchSeason: 'Insurance-contract renegotiation',
    scene: 'A confident new smile',
  },
  {
    id: 'veterinary-clinic',
    label: 'Veterinary Clinic',
    venture: 'clinic',
    team: 'veterinary team',
    customers: 'pet owners',
    pressureLabel: 'Corporate roll-ups & burnout attrition',
    pressureDesc:
      'Consolidators buy the clinic next door and poach exhausted staff; appointment capacity erodes exactly as demand peaks.',
    pressureSources: 'consolidator territories',
    gearTerm: 'Exam rooms & surgical suite',
    inquiriesTerm: 'Appointment calls',
    peakSeason: 'Spring vaccine season',
    slowSeason: 'Mid-winter quiet',
    crunchSeason: 'Locum shortage',
    scene: 'A recovered patient going home',
  },
  {
    id: 'yoga-studio',
    label: 'Yoga Studio',
    venture: 'studio',
    team: 'instructors',
    customers: 'practitioners',
    pressureLabel: 'Streaming substitutes & pass-app dilution',
    pressureDesc:
      'Living-room streaming and multi-studio pass apps dilute loyalty; unattended, the core membership dissolves into drop-ins.',
    pressureSources: 'pass-app crowds',
    gearTerm: 'Studio rooms & props',
    inquiriesTerm: 'Intro-offer sign-ups',
    peakSeason: 'New-year intention wave',
    slowSeason: 'High-summer exodus',
    crunchSeason: 'Membership-budget cuts',
    scene: 'Sunset flow by candlelight',
  },
  {
    id: 'barbershop',
    label: 'Barbershop',
    venture: 'shop',
    team: 'barbers',
    customers: 'regulars',
    pressureLabel: 'Chair turnover & discount chains',
    pressureDesc:
      'Star barbers take their books solo while discount chains undercut walk-ins; a shop that stops earning loyalty loses a chair a quarter.',
    pressureSources: 'poached client books',
    gearTerm: 'Chairs & clipper kits',
    inquiriesTerm: 'Walk-ins & bookings',
    peakSeason: 'Event & holiday grooming rush',
    slowSeason: 'Grow-out weeks',
    crunchSeason: 'High-street footfall slump',
    scene: 'A sharp fade in the mirror',
  },
  {
    id: 'nail-salon',
    label: 'Nail Salon',
    venture: 'salon',
    team: 'technicians',
    customers: 'clients',
    pressureLabel: 'Price wars & no-show erosion',
    pressureDesc:
      'Neighboring salons race prices down while no-shows hollow the book; margins decay chair by chair without deliberate rebooking.',
    pressureSources: 'price-war blocks',
    gearTerm: 'Stations & UV lamps',
    inquiriesTerm: 'Appointment bookings',
    peakSeason: 'Wedding & prom season',
    slowSeason: 'January quiet',
    crunchSeason: 'Supply-cost spike',
    scene: 'A flawless gel set',
  },
  {
    id: 'tattoo-studio',
    label: 'Tattoo Studio',
    venture: 'studio',
    team: 'artists',
    customers: 'collectors',
    pressureLabel: 'Scene churn & flash-price undercutting',
    pressureDesc:
      'Guest artists lure your following and cut-rate flash shops cheapen the market; without fresh work in the feed, deposits dry up.',
    pressureSources: 'undercutting walk-in shops',
    gearTerm: 'Stations & sterilization gear',
    inquiriesTerm: 'Consultation requests',
    peakSeason: 'Convention season',
    slowSeason: 'Post-holiday quiet',
    crunchSeason: 'Discretionary-spend freeze',
    scene: 'A finished full-sleeve reveal',
  },
  {
    id: 'escape-room-venue',
    label: 'Escape Room Venue',
    venture: 'venue',
    team: 'game masters',
    customers: 'teams',
    pressureLabel: 'Novelty decay & competitor room churn',
    pressureDesc:
      'A room everyone has played stops selling; rivals launch fresh themes quarterly and stale inventory bleeds weekend slots.',
    pressureSources: 'played-out rooms',
    gearTerm: 'Room sets & prop systems',
    inquiriesTerm: 'Slot bookings',
    peakSeason: 'Rainy-weekend high season',
    slowSeason: 'Sunny-summer dip',
    crunchSeason: 'Corporate-events freeze',
    scene: 'A team beating the clock',
  },
  {
    id: 'axe-throwing-lounge',
    label: 'Axe Throwing Lounge',
    venture: 'lounge',
    team: 'lane coaches',
    customers: 'groups',
    pressureLabel: 'Fad fade & insurance creep',
    pressureDesc:
      'The novelty curve flattens while insurance premiums climb; unprogrammed lanes go quiet midweek and stay quiet.',
    pressureSources: 'dead midweek lanes',
    gearTerm: 'Lanes & target walls',
    inquiriesTerm: 'Group bookings',
    peakSeason: 'Party season',
    slowSeason: 'January hush',
    crunchSeason: 'Premium-renewal squeeze',
    scene: 'A bullseye on the first throw',
  },
  {
    id: 'mini-golf-course',
    label: 'Mini Golf Course',
    venture: 'course',
    team: 'course staff',
    customers: 'families',
    pressureLabel: 'Weather washouts & attraction sprawl',
    pressureDesc:
      'Every rainy weekend is unrecoverable revenue and each new mall attraction skims birthday parties; an unrefreshed course fades from the rotation.',
    pressureSources: 'washed-out weekends',
    gearTerm: 'Holes & putters',
    inquiriesTerm: 'Party bookings',
    peakSeason: 'Summer holidays',
    slowSeason: 'School-term weekdays',
    crunchSeason: 'Storm-season stretch',
    scene: 'A hole-in-one celebration',
  },
  {
    id: 'climbing-gym',
    label: 'Climbing Gym',
    venture: 'gym',
    team: 'route setters',
    customers: 'climbers',
    pressureLabel: 'Route staleness & mega-gym expansion',
    pressureDesc:
      'Stale routes push regulars toward the new mega-gym across town; without constant resetting, day passes and memberships slide together.',
    pressureSources: 'stale walls',
    gearTerm: 'Walls & holds inventory',
    inquiriesTerm: 'Day-pass sales',
    peakSeason: 'Indoor winter season',
    slowSeason: 'Outdoor summer exodus',
    crunchSeason: 'Membership-market saturation',
    scene: 'Topping out a project route',
  },
  {
    id: 'surf-school',
    label: 'Surf School',
    venture: 'school',
    team: 'instructors',
    customers: 'students',
    pressureLabel: 'Flat spells & beach-permit rivalry',
    pressureDesc:
      'Flat weeks refund themselves and rival schools bid up the best beach permits; an idle calendar drains cash while the vans sit.',
    pressureSources: 'contested beach breaks',
    gearTerm: 'Boards & wetsuit fleet',
    inquiriesTerm: 'Lesson bookings',
    peakSeason: 'Summer swell',
    slowSeason: 'Cold-water months',
    crunchSeason: 'Permit-auction squeeze',
    scene: 'A first ride all the way to shore',
  },
  {
    id: 'ski-rental-shop',
    label: 'Ski Rental Shop',
    venture: 'shop',
    team: 'fitting techs',
    customers: 'skiers',
    pressureLabel: 'Snow variability & resort-shop competition',
    pressureDesc:
      'Thin snow years gut the season while the resort pushes its own rental counter; every warm week erodes the fleet’s payback math.',
    pressureSources: 'bare-slope weeks',
    gearTerm: 'Ski & boot fleet',
    inquiriesTerm: 'Reservation volume',
    peakSeason: 'Powder season',
    slowSeason: 'Green summer',
    crunchSeason: 'Low-snow winter',
    scene: 'First tracks on a powder morning',
  },
  {
    id: 'bike-repair-shop',
    label: 'Bike Repair Shop',
    venture: 'shop',
    team: 'mechanics',
    customers: 'riders',
    pressureLabel: 'Direct-to-consumer drift & parts backlogs',
    pressureDesc:
      'Online direct brands bypass the workshop while parts backlogs stall the stand; a slow bench loses riders to the next suburb.',
    pressureSources: 'backordered part queues',
    gearTerm: 'Work stands & tool walls',
    inquiriesTerm: 'Service bookings',
    peakSeason: 'Spring tune-up rush',
    slowSeason: 'Deep-winter quiet',
    crunchSeason: 'Supply-chain backlog',
    scene: 'A rebuilt classic rolling out',
  },
  {
    id: 'auto-detailing',
    label: 'Auto Detailing Studio',
    venture: 'studio',
    team: 'detailers',
    customers: 'car owners',
    pressureLabel: 'Drive-through undercutting & booking churn',
    pressureDesc:
      'Five-dollar drive-throughs anchor prices low while weather cancellations shred the calendar; an idle bay burns rent by the hour.',
    pressureSources: 'discount wash strips',
    gearTerm: 'Bays & polishing rigs',
    inquiriesTerm: 'Detail bookings',
    peakSeason: 'Show-season spring',
    slowSeason: 'Salt-and-slush winter',
    crunchSeason: 'Luxury-spend pullback',
    scene: 'A mirror finish under the lights',
  },
  {
    id: 'ev-charging-installer',
    label: 'EV Charger Installation Company',
    venture: 'company',
    team: 'install crews',
    customers: 'property owners',
    pressureLabel: 'Incentive whiplash & bid competition',
    pressureDesc:
      'Rebate programs lurch open and shut while national installers bid below cost to buy the market; the pipeline decays whenever policy stalls.',
    pressureSources: 'stalled rebate queues',
    gearTerm: 'Vans & commissioning kit',
    inquiriesTerm: 'Site-survey requests',
    peakSeason: 'Rebate-window rush',
    slowSeason: 'Policy-gap lull',
    crunchSeason: 'Grant-freeze quarter',
    scene: 'A commissioning light turning green',
  },
  {
    id: 'solar-panel-installer',
    label: 'Solar Installation Company',
    venture: 'company',
    team: 'install crews',
    customers: 'homeowners',
    pressureLabel: 'Tariff swings & lead-gen saturation',
    pressureDesc:
      'Feed-in tariffs wobble, cheap lead brokers spam your patch, and every policy headline stalls signatures; the funnel silts up fast.',
    pressureSources: 'lead-broker turf',
    gearTerm: 'Racking & inverter stock',
    inquiriesTerm: 'Quote requests',
    peakSeason: 'High-sun quarter',
    slowSeason: 'Short-day winter',
    crunchSeason: 'Tariff-review freeze',
    scene: 'An array going live at noon',
  },
  {
    id: 'plumbing-company',
    label: 'Plumbing Company',
    venture: 'company',
    team: 'service techs',
    customers: 'households',
    pressureLabel: 'Apprentice shortage & platform lead fees',
    pressureDesc:
      'Lead platforms tax every job while the trade pipeline produces fewer apprentices than retirements; unstaffed vans equal unanswered emergencies.',
    pressureSources: 'unfilled van rosters',
    gearTerm: 'Vans & jetting rigs',
    inquiriesTerm: 'Emergency calls',
    peakSeason: 'Freeze-burst winter',
    slowSeason: 'Mild-weather lull',
    crunchSeason: 'Insurance-work backlog',
    scene: 'A burst pipe saved before the ceiling',
  },
  {
    id: 'electrician-service',
    label: 'Electrical Services Company',
    venture: 'company',
    team: 'sparkies',
    customers: 'clients',
    pressureLabel: 'Compliance churn & bid undercutting',
    pressureDesc:
      'Code revisions demand constant recertification while fly-by-night bidders undercut quotes; the compliance treadmill eats unbilled hours.',
    pressureSources: 'undercut tender lists',
    gearTerm: 'Test rigs & van stock',
    inquiriesTerm: 'Job inquiries',
    peakSeason: 'Renovation spring',
    slowSeason: 'Holiday shutdown',
    crunchSeason: 'Construction-sector slump',
    scene: 'A panel upgrade passing inspection',
  },
  {
    id: 'hvac-service',
    label: 'HVAC Service Company',
    venture: 'company',
    team: 'service techs',
    customers: 'building owners',
    pressureLabel: 'Seasonal whiplash & refrigerant regulation',
    pressureDesc:
      'Demand spikes with heat waves then vanishes with mild weeks, while refrigerant phase-outs strand inventory; feast-famine cycles wreck steady payroll.',
    pressureSources: 'mild-week troughs',
    gearTerm: 'Gauges & recovery machines',
    inquiriesTerm: 'Service calls',
    peakSeason: 'Heat-wave summer',
    slowSeason: 'Mild shoulder weeks',
    crunchSeason: 'Refrigerant phase-out',
    scene: 'Cold air on the hottest day',
  },
  {
    id: 'roofing-company',
    label: 'Roofing Company',
    venture: 'company',
    team: 'roofing crews',
    customers: 'homeowners',
    pressureLabel: 'Storm-chaser flooding & material inflation',
    pressureDesc:
      'Out-of-town storm chasers flood in after every hail event and vanish with deposits, poisoning trust; shingle inflation squeezes every fixed bid.',
    pressureSources: 'storm-chaser sweeps',
    gearTerm: 'Lifts & tear-off tools',
    inquiriesTerm: 'Inspection requests',
    peakSeason: 'Post-storm surge',
    slowSeason: 'Frozen-deck winter',
    crunchSeason: 'Material-inflation spike',
    scene: 'A finished ridge line at sunset',
  },
  {
    id: 'moving-company',
    label: 'Moving Company',
    venture: 'company',
    team: 'moving crews',
    customers: 'movers',
    pressureLabel: 'Marketplace brokers & damage-claim drag',
    pressureDesc:
      'Broker marketplaces skim the easy jobs and forward the nightmares; one viral damage claim undoes a season of five-star reviews.',
    pressureSources: 'broker-skimmed routes',
    gearTerm: 'Trucks & dollies',
    inquiriesTerm: 'Quote requests',
    peakSeason: 'Lease-turnover summer',
    slowSeason: 'Deep-winter freeze',
    crunchSeason: 'Housing-market stall',
    scene: 'The last box in the new home',
  },
  {
    id: 'self-storage-facility',
    label: 'Self-Storage Facility',
    venture: 'facility',
    team: 'site managers',
    customers: 'tenants',
    pressureLabel: 'REIT overbuilding & rate-shopping churn',
    pressureDesc:
      'Institutional operators overbuild the corridor and price intro rates below cost; rate-shopping tenants churn the roll every renewal.',
    pressureSources: 'overbuilt corridors',
    gearTerm: 'Units & gate systems',
    inquiriesTerm: 'Unit inquiries',
    peakSeason: 'Moving season',
    slowSeason: 'Mid-winter stasis',
    crunchSeason: 'Rate-war quarter',
    scene: 'A clean, lit corridor of doors',
  },
  {
    id: 'laundromat',
    label: 'Neighborhood Laundromat',
    venture: 'laundromat',
    team: 'attendants',
    customers: 'neighbors',
    pressureLabel: 'In-unit washer creep & utility inflation',
    pressureDesc:
      'Every renovated building adds in-unit washers while water and power rates climb; unattended machines age into out-of-order signs.',
    pressureSources: 'renovated blocks',
    gearTerm: 'Washer & dryer fleet',
    inquiriesTerm: 'Wash-and-fold orders',
    peakSeason: 'Student move-in autumn',
    slowSeason: 'Summer vacancy',
    crunchSeason: 'Utility-rate spike',
    scene: 'Warm folded laundry at closing time',
  },
  {
    id: 'dry-cleaner',
    label: 'Dry Cleaning Shop',
    venture: 'shop',
    team: 'pressers',
    customers: 'clients',
    pressureLabel: 'Casualization & solvent regulation',
    pressureDesc:
      'Office dress codes relax season by season while solvent rules force equipment turnover; the rack thins as suits leave wardrobes.',
    pressureSources: 'casual-code offices',
    gearTerm: 'Presses & conveyor racks',
    inquiriesTerm: 'Garment drop-offs',
    peakSeason: 'Wedding & gala season',
    slowSeason: 'Remote-work summer',
    crunchSeason: 'Equipment-compliance deadline',
    scene: 'A pressed suit ready for the aisle',
  },
  {
    id: 'florist',
    label: 'Florist Shop',
    venture: 'shop',
    team: 'floral designers',
    customers: 'gift-givers',
    pressureLabel: 'Supermarket bunches & wire-service fees',
    pressureDesc:
      'Grocery buckets anchor prices while wire services take a third of every relayed order; unsold stems compost the margin nightly.',
    pressureSources: 'wire-service dependence',
    gearTerm: 'Coolers & design benches',
    inquiriesTerm: 'Arrangement orders',
    peakSeason: 'Peak romance week',
    slowSeason: 'Post-holiday hush',
    crunchSeason: 'Cold-chain cost spike',
    scene: 'A bridal bouquet coming together',
  },
  {
    id: 'garden-center',
    label: 'Garden Center',
    venture: 'center',
    team: 'horticulturists',
    customers: 'gardeners',
    pressureLabel: 'Big-box seasonal aisles & weather whiplash',
    pressureDesc:
      'Big-box stores stack cut-price seedlings every spring while a late frost can kill a quarter’s stock on the benches.',
    pressureSources: 'big-box garden aisles',
    gearTerm: 'Greenhouses & benches',
    inquiriesTerm: 'Seasonal footfall',
    peakSeason: 'Planting spring',
    slowSeason: 'Dormant winter',
    crunchSeason: 'Late-frost shock',
    scene: 'Greenhouse benches in full bloom',
  },
  {
    id: 'bookstore-cafe',
    label: 'Bookstore Café',
    venture: 'shop',
    team: 'booksellers',
    customers: 'readers',
    pressureLabel: 'Online discounting & browse-only drift',
    pressureDesc:
      'Online megastores discount below cost and browsers photograph covers to buy elsewhere; the till decays even when the aisles feel busy.',
    pressureSources: 'showrooming aisles',
    gearTerm: 'Shelves & espresso bar',
    inquiriesTerm: 'Event RSVPs',
    peakSeason: 'Holiday gifting season',
    slowSeason: 'January quiet',
    crunchSeason: 'Distributor-terms squeeze',
    scene: 'A packed author reading night',
  },
  {
    id: 'record-store',
    label: 'Independent Record Store',
    venture: 'store',
    team: 'crate curators',
    customers: 'collectors',
    pressureLabel: 'Pressing-plant queues & streaming gravity',
    pressureDesc:
      'Pressing backlogs delay releases for months while streaming keeps casual buyers home; bins stagnate without fresh arrivals.',
    pressureSources: 'delayed release queues',
    gearTerm: 'Bins & listening stations',
    inquiriesTerm: 'Drop-day turnout',
    peakSeason: 'Record-fair season',
    slowSeason: 'Mid-summer lull',
    crunchSeason: 'Pressing-cost spike',
    scene: 'A first pressing found in the bins',
  },
  {
    id: 'art-gallery',
    label: 'Contemporary Art Gallery',
    venture: 'gallery',
    team: 'curators',
    customers: 'collectors',
    pressureLabel: 'Fair-circuit costs & artist poaching',
    pressureDesc:
      'Art-fair booths burn cash whether work sells or not, and bigger galleries poach breakout artists the moment prices move.',
    pressureSources: 'poaching mega-galleries',
    gearTerm: 'Exhibition space & lighting',
    inquiriesTerm: 'Collector inquiries',
    peakSeason: 'Fair season',
    slowSeason: 'August closure',
    crunchSeason: 'Collector-confidence dip',
    scene: 'Opening night red dots',
  },
  {
    id: 'pottery-studio',
    label: 'Pottery Studio',
    venture: 'studio',
    team: 'teaching potters',
    customers: 'students',
    pressureLabel: 'Class churn & kiln economics',
    pressureDesc:
      'Hobby students cycle out after one term while kiln firings cost the same half-empty or full; unfilled wheels quietly sink the month.',
    pressureSources: 'half-empty class blocks',
    gearTerm: 'Wheels & kilns',
    inquiriesTerm: 'Class sign-ups',
    peakSeason: 'Autumn enrollment wave',
    slowSeason: 'Summer drop-off',
    crunchSeason: 'Energy-price surge',
    scene: 'A kiln opening full of glazed work',
  },
  {
    id: 'music-school',
    label: 'Community Music School',
    venture: 'school',
    team: 'teaching faculty',
    customers: 'students',
    pressureLabel: 'Schedule attrition & app-lesson substitutes',
    pressureDesc:
      'Sports seasons and app-based lessons erode weekly attendance; every un-refilled 4pm slot compounds across the term.',
    pressureSources: 'empty afternoon slots',
    gearTerm: 'Practice rooms & instruments',
    inquiriesTerm: 'Trial-lesson requests',
    peakSeason: 'Recital-prep term',
    slowSeason: 'Summer holidays',
    crunchSeason: 'Extracurricular budget cuts',
    scene: 'A nervous first recital nailed',
  },
  {
    id: 'dance-academy',
    label: 'Dance Academy',
    venture: 'academy',
    team: 'instructors',
    customers: 'dancers',
    pressureLabel: 'Competition-team costs & enrollment churn',
    pressureDesc:
      'Competition fees climb yearly while rival academies flash bigger trophies; families drift at every season break unless re-enrolled deliberately.',
    pressureSources: 'rival trophy walls',
    gearTerm: 'Sprung floors & mirrors',
    inquiriesTerm: 'Trial-class bookings',
    peakSeason: 'Competition season',
    slowSeason: 'Post-recital summer',
    crunchSeason: 'Family-budget squeeze',
    scene: 'A first-place team routine',
  },
  {
    id: 'podcast-production-studio',
    label: 'Podcast Production Studio',
    venture: 'studio',
    team: 'producers',
    customers: 'shows',
    pressureLabel: 'DIY tooling & ad-market softness',
    pressureDesc:
      'One-click editing tools swallow the low end while ad-market dips pause client budgets; retainers decay into one-off edits.',
    pressureSources: 'DIY-tool churn',
    gearTerm: 'Booths & mixing desks',
    inquiriesTerm: 'Production inquiries',
    peakSeason: 'Launch-season autumn',
    slowSeason: 'Summer hiatus',
    crunchSeason: 'Ad-spend pullback',
    scene: 'A chart debut for a client show',
  },
  {
    id: 'wedding-venue',
    label: 'Wedding & Events Venue',
    venture: 'venue',
    team: 'events team',
    customers: 'couples',
    pressureLabel: 'Date-inventory decay & venue oversupply',
    pressureDesc:
      'Every unbooked Saturday expires worthless while new barns and lofts open each year; the calendar decays date by date without pipeline work.',
    pressureSources: 'unbooked prime dates',
    gearTerm: 'Halls & grounds',
    inquiriesTerm: 'Tour requests',
    peakSeason: 'Peak wedding season',
    slowSeason: 'Deep-winter gap',
    crunchSeason: 'Engagement-rate dip',
    scene: 'First dance under the lights',
  },
  {
    id: 'bed-and-breakfast',
    label: 'Bed & Breakfast',
    venture: 'inn',
    team: 'innkeepers',
    customers: 'guests',
    pressureLabel: 'OTA commissions & short-stay saturation',
    pressureDesc:
      'Booking platforms take a fifth of every night while short-stay apartments flood the town; direct bookings decay without constant cultivation.',
    pressureSources: 'platform-saturated streets',
    gearTerm: 'Guest rooms & kitchen',
    inquiriesTerm: 'Booking requests',
    peakSeason: 'Tourist high season',
    slowSeason: 'Off-season quiet',
    crunchSeason: 'Travel-demand shock',
    scene: 'Breakfast service in the garden',
  },
  {
    id: 'kayak-tour-operator',
    label: 'Kayak Tour Company',
    venture: 'outfit',
    team: 'guides',
    customers: 'paddlers',
    pressureLabel: 'Weather cancellations & permit caps',
    pressureDesc:
      'Wind days refund themselves, launch permits cap capacity, and cut-price operators crowd the put-in; idle boats rot the season’s math.',
    pressureSources: 'blown-out tour days',
    gearTerm: 'Kayak & trailer fleet',
    inquiriesTerm: 'Tour bookings',
    peakSeason: 'Calm-water summer',
    slowSeason: 'Storm-window shoulder',
    crunchSeason: 'Permit-lottery squeeze',
    scene: 'A glassy sunrise paddle-out',
  },
];
